### ISSUE TITLE
DeepPureRenderMixin prevents GridItem children from rendering

### ISSUE THREAD

**Issue by benmosher** [STRML/react-grid-layout#105]
I just ran into a wild issue where my grid would not update even though props were changing, likely similar to #102.

Digging into the code, I see the DeepPureRenderMixin is mixed into both the grid layout and the item wrapper.

At first blush, deep equality for props seems like it should always be correct, so I figured that must not be the problem.

After some digging in, though, in this case, but it turned out the problem was that the prop that was changing is always a `Promise`, and apparently `deepEqual(aPromise, bPromise)` is `true` for all `aPromise`, `bPromise`.

I have some code that uses frozen objects as `WeakMap` keys into Flux stores, as well, and these objects are not guaranteed to be distinct in value. I assume these would also fail to re-render on account of potentially being deeply equal.

Given all that, and after re-reading the [React docs explanation of PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html), I would argue that as a library component, neither the grid layouts nor the grid item components should implement `shouldComponentUpdate`. The responsibility to implement this should instead fall on the importing application author.

The application author ought to be able to get the same perf improvements by implementing `shouldComponentUpdate` in the parent component of the GridLayout, and / or the child component of the GridItem.

If there are expensive regions of code in either the grid layout or item `render()` methods, instead of relying on `shouldComponentUpdate`, the component could cache the results of the expensive bits and only update these cached results if necessary, inside of `componentWillReceiveProps`.

I have a fork where I modified 0.8.5 to remove the `shouldComponentUpdate` implementation, and performance did not seem to significantly degrade. I can open a PR, but I though it would be good to discuss first.

**Comment by STRML** [comment]
:+1: I think you're right about this. I've seen a few tickets pop up with issues related to PDRM. I've included it because there is not a way, otherwise, to prevent rerendering of all grid items when moving one item. It may just be that this overhead is worth it in order to prevent these kind of hard-to-find bugs.

**Comment by benmosher** [comment]
I think that makes sense. And again, assuming the grid item can be smart about its own `render()`-time execution, it's up to the application to properly implement `shouldComponentUpdate()` in the children to prevent repaints (if they're heavy).

Would you be up for creating an 0.8.x branch that I could submit the PR against? From perusing some of the other open issues, I'm assuming 0.9.x is not ready for re-release soon. I am imagining this could be released as 0.8.6 in the short term?

If not, I'm fine to submit against `master` and I can use my fork in the interim.

**Comment by Jero786** [comment]
Hello! In my case I have a big grid, and I need the Item are dynamic (static:false) until start draggin that I turn to static:true in order to dont move the items during draggin process, and after when stop dragging, I put all item again static:false. This are a expensive rendering cycle, so for that, I want to only re-rendering grid items that are in the current viewport. I thinking to use `componentShouldUpdate` in each of grid item, but I couldn't it work. 

How could be the way to archive that?

Very thanks!

**Comment by STRML** [comment]
PureDeepRenderMixin is gone. Thanks @benmosher.

If you want to implement a custom `shouldComponentUpdate`, you could always monkey-patch the prototypes.

**Comment by Jero786** [comment]
@STRML could make some example with that solution?? Thanks very much!
