### ISSUE TITLE
Allow overlap of the components inside the ReactGridLayout

### ISSUE THREAD

**Issue by jackhts4** [STRML/react-grid-layout#1062]
Would like to ask if there is a function to let the components inside ReactGridLayout allowed to overlap, that is without the auto layout?

**Comment by nagasudhirpulla** [comment]
> Would like to ask if there is a function to let the components inside ReactGridLayout allowed to overlap, that is without the auto layout?

I am also in need of this feature

**Comment by ACPrice** [comment]
This would be handy for something I'm working on as well. Thanks for the great library!

**Comment by nagasudhirpulla** [comment]
Please implement this feature...

**Comment by wsheehan** [comment]
I'm interested in this feature as well, willing to write an initial implementation, just want to make sure nobody else is working on it?

**Comment by mattmillerart** [comment]
@wsheehan did you make any progress on this?

**Comment by sehilyi** [comment]
Any progress on this feature?

**Comment by mirceaciu** [comment]
Couldn't find anything on this feature except for this related request #677 (It might be possible to make the elements overlap by grammatically changing their props, but only after initialization)

Maybe overlapping is difficult because then z-index would also have to be managed somehow, and there is already and issue on that #858
