### ISSUE TITLE
 Change isResizable or isDraggable will recreate all the block of layout

### ISSUE THREAD

**Issue by fred8617** [STRML/react-grid-layout#1067]
https://codesandbox.io/s/laughing-pine-5jgly

**Comment by concha-secmotic** [comment]
Same issue here. As the grid becomes more complex, performance drops a lot...

**Comment by omercavuslu** [comment]
+

**Comment by cjacksudo** [comment]
+1

**Comment by sterzhakov** [comment]
+1 and for static property

**Comment by robinhood23rus** [comment]
+1

**Comment by msiomkin** [comment]
+1

**Comment by msiomkin** [comment]
+1

**Comment by dson** [comment]
I ran into this issue as well. I think it is caused by these two lines: https://github.com/STRML/react-grid-layout/blob/master/lib/GridItem.jsx#L554-L558.

The child is conditionally wrapped with two mixins. When one of the conditions changes, React has to recreate the entire tree from that point. All nested React components are recreated as well, thereby loosing their state. This may cause flashing of content, expensive server calls or unnecessary re-initialization.

A solution would be to always wrap the child with those two mixins, and be able to disable the mixin's behavior by passing a prop to the mixin.

**Comment by JohnDDuncanIII** [comment]
I am also running into this issue and found @foodforarabbit's workaround in https://github.com/STRML/react-grid-layout/issues/721#issuecomment-364622648 helpful.

It looks like there is also a PR that is attempting to address this issue as well https://github.com/STRML/react-grid-layout/pull/892

**Comment by STRML** [comment]
Fixed in #892.
