### ISSUE TITLE
Updating cols doesn't update the GridLayout v.0.17.1

### ISSUE THREAD

**Issue by misha-panyushkin** [STRML/react-grid-layout#1122]
Colleagues, I want to note that the new version has ceased to support previously announced functionality (v0.16.6). In particular, it does not recount ResponsiveGridLayout when updating columns:

https://codesandbox.io/s/polished-https-v9sb5

**Comment by misha-panyushkin** [comment]
@STRML any updates on it?

**Comment by kudlav** [comment]
@STRML Please reopen this issue, because it's serious issue and still not fixed. And would be great if you could kill this annoying github-action bot, because it's not for the first time when it closed active issue. Otherwise I will have to open new issue.

**Comment by kudlav** [comment]
@misha-panyushkin 
Looked into the code and found the bug. The bug is already fixed but not uploaded into npm repository. So here is workaround, install dependency from github:
`npm i STRML/react-grid-layout#master --save-dev`

or go into `node_modules/react-grid-layout/build/ResponsiveReactGridLayout.js` and change line  187:
`if (lastBreakpoint !== newBreakpoint || this.state.breakpoints !== breakpoints || this.state.cols !== cols) {`
