### ISSUE TITLE
Any update on a stable release and 0.14 support? 

### ISSUE THREAD

**Issue by tuckwat** [STRML/react-grid-layout#113]
I'm having issues getting the latest react-grid-layout to work properly.  I've tested React 0.13.3 and 0.14, both have the same issue (although 0.14 has additional warnings).  I'm using:

* npm:react-grid-layout@0.8.5
* npm:react-resizable@0.4.2
* npm:react-draggable@0.8.4

Resizing GridItems is buggy, the initial drag causes the width to jump to around 2x the GridItem width.  I've tried a few different versions back of both react-resizable and react-draggable but can't find a working combo.

**Comment by abhas9** [comment]
+1
I am having same problem.

**Comment by franferdez** [comment]
Same here.

**Comment by pvw87** [comment]
+1
Same Here

**Comment by STRML** [comment]
It's coming along. Been very busy with other projects. Both Draggable and
Resizable are about 80 percent through a rewrite. I'll prioritize this
soon, I want to get RGL in a production app by the end of the month.

Sorry for the delay - this has had to take the back burner to some other
projects.

**Comment by tuckwat** [comment]
No worries, completely understand.  Anything in particular that needs assistance?

**Comment by NoahMarconi** [comment]
Aside from the rewrite, can you point us in the right direction to fix this bug? 

If it helps, setting `useCSSTransforms={true}` gets rid of any dragging related problem I had. The remaining one is with resizing.

When resizing, even dragging a little causes a big jump in size.

If instead of making the grid item bigger, I resize by dragging to the top left corner of the client, so that clientX and clientY are both zero; no jump. I can then continue dragging until clientX and  clientY are 20 (so about 20 pixels from the top left) and the grid item resizes to add about 20 pixels to the height and width.

Is there a translate or an offeset that's not triggering to take into consideration that resize started from the bottom left of the grid item?



I compared my local version's behaviour to your live demo and in the resizeHandler `var position = ref.position` behaves differently between the two.

In your live demo top and left always refer to the distance in pixels from where I started dragging. In the local version that I'm running (after upgrading to react 0.15) top and left refer to distance from the client's top/left corner.

I can't see if this is a draggable, resizable, or rgl bug in order to try to fix it.

**Comment by NoahMarconi** [comment]
ok, I dug deeper. There are a couple of things going on but one of them is that the state is not being set for offsetX and offsetY in dragable.

```{javascript}
    // Initiate dragging. Set the current x and y as offsets
    // so we know how much we've moved during the drag. This allows us
    // to drag elements around even if they have been moved, without issue.
    this.setState({
      dragging: true,
      offsetX: dragPoint.clientX - this.state.clientX,
      offsetY: dragPoint.clientY - this.state.clientY,
      scrollX: document.body.scrollLeft,
      scrollY: document.body.scrollTop
    });
```

I added a global variable and referenced that instead of state and it kind of works but is still a jumpy:

```{javascript}
    offsetX = dragPoint.clientX - this.state.clientX;
    offsetY = dragPoint.clientY - this.state.clientY;
```

Is there anything we can do to lend a hand with the last 20% of the rewrite?

**Comment by pstoellberger** [comment]
+1 - react 0.14 incompatible with dependencies from react-grid-layout: 0.8.5

**Comment by Aweary** [comment]
@STRML you may want to consider finding some additional devs to add as collaborators to help you with the workload for this project, since it's quite popular.

**Comment by dmr** [comment]
What can I do to help?

There are some forks which provide 0.14 support.
Are there any plans to merge them?

**Comment by NeXTs** [comment]
@STRML Please tell us at least approximately when to expect a new release?

**Comment by STRML** [comment]
@NeXTs I'm working on it in the `next` branch. This is a complicated transition and I'm perpetually short on time. The magic of open source is, anyone can help out.

**Comment by pnuzhdin** [comment]
@STRML Regarding the help. What was done in the ```next``` branch at this moment and what should be done to finish the transition?

**Comment by levona** [comment]
+1
Same here

**Comment by tlrobinson** [comment]
+1

**Comment by STRML** [comment]
`0.10.2` is out and stable. Please open new issues if you have any.
