### ISSUE TITLE
Grid item with set to bigger width not re-growing after shrinking due to window resize

### ISSUE THREAD

**Issue by agmcleod** [STRML/react-grid-layout#1135]
Apologies if this is intentional behaviour, but having an issue where i say set a grid item to 4,2 dimensions. I shrink the screen so its width reduces. When I increase the size of the window, the item does not go back to its previous size. I had trouble in the sandbox initializing the item to a bigger size, but if you increase the size and then shrink the screen, the grow the screen, you can see what i am referring to.

https://codesandbox.io/s/floral-voice-1mgkf

**Comment by eric-burel** [comment]
I am not sure I understood your issue but a `window.dispatchEvent(new Event('resize')` triggers a width recomputation so it may help if you layout does not update automatically after some element size changed. Sometime I also need to wrap it in a setTimeout(..., 1) so that the size is correctly recomputed on next frame only. WidthProvider can listen to window resize, but not if a dom element is resized (it is not doable), it may explain widgth not updating.

**Comment by agmcleod** [comment]
@eric-burel hey eric, i was just about to post an update.

Looks like the issue was on my end. I was passing the current layout from the onLayout event to the server. The issue is, this then became the source of truth from what i would then pass to the layout prop, for lg & sm sizes. I experimented yesterday on using the allLayouts from onlayout event instead, and this has gave me a much better experience.

Thank you though for your reply :)
