### ISSUE TITLE
External layout update (Subscriptions) not working

### ISSUE THREAD

**Issue by BerenLuth** [STRML/react-grid-layout#1181]
First of all thanks for the library, it's perfect for my use case!

**Use Case:**
When I have more clients connected and someone moves an element I want to synchronize the position, in order to do so, I notify the other clients through subscriptions.

**Problem:**
I want to update the layout manually but it looks like there's no way to do so

**Solutions tried:**
- I generate the children inside the layout so they naturally have the new indexes once the array is updated, but apart from during the initial creation, it doesn't affect the layout position.
- I tried to set the Layout variable from a React state variable rather than setting parameters on the children, and once the subscription is called, I manually update the layout's positions, I set them trough React useState, but again it doesn't affect the actual visible layout

Is there any way to force the update of the positions?

**Comment by mahmutyilmazcs** [comment]
I have the same issue, and I think, lib doesn't count on layout change on children without a drag drop. I mean, you can't change position of your items arbitrarily. You could change their keys to force update, but it shouldn't be done so since they are not different items, they just have different positions/layouts.

The reason for that is the possibility of an item having layout change is discarded when updating layout in utils' **synchronizeLayoutWithChildren** function.

line 649 
currently:  `layout[i] = cloneLayoutItem(exists);`
but should(?) be:  `layout[i] = child.props["data-grid"] || cloneLayoutItem(exists);`

Is there any other way to do it or my approach is correct?.

**Comment by c-ctkd** [comment]
I have the same issue and also happens when i change the dimensions of the LayoutItems without using the layout resize function (my items have fixed dimensions instead of user defined).

**Comment by c-ctkd** [comment]
after some time i was able to find a way to update the items position on multiple clients using subscriptions.

First i generate a Layout array that will be passed in the layout props of the ReactGridLayout, this layout array is also updated when the subscription sends new data, then i generate the children based on that layout array. You have to make sure the "i" property of the layout is the same as the "key" value of the children on that positon.

ex:

```
//when the subscription receives new data updates/creates layout array
const layoutArr = someData.map(
(data) => {i: data.key, x: data.xPos, y: data.yPos, w:data.width, h: data.height}
);


....
render () {

//generate children based on the layoutArr data
const children = this.layoutArr.map((layout) => {
  return (
    <div key={layout.i}>
       <MyItem width={layout.width} height={layout.height} />
    </div>
    );
});

// i use onDragStop to set the new items position on the bd
return(
  <ReactGridLayout layout={layoutArr } onDragStop={this.handleDragStop}>
    {children}
  </ReactGridLayout>
 );
};
```

on my case this works because i use the x and y to set the items position also solves the resize problem

**Comment by BerenLuth** [comment]
Still not working, basically I had the same code already, the only difference was in the "i" property, but even after adding it, it doesn't work
