### ISSUE TITLE
Is there an option to allow resizing to a height with decimal places?

### ISSUE THREAD

**Issue by GeneFTBC** [STRML/react-grid-layout#1187]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

So i initialise my grid with the following,
`{
      width: 2,
      height: 1.5,
      minWidth: 1,
      maxWidth: 4
    };`
Now, when I resize this item, I cant revert it back to the original height(1.5). Is there a way to allow setting height with .5 values?

**Comment by romanpastu** [comment]
Having the same issue there

**Comment by bunge12** [comment]
Same issue here

**Comment by Michael-Xie** [comment]
Would love to see if there is any update to this issue

**Comment by STRML** [comment]
There is no way to do this built into the library. I would suggest simply doubling your grid units.

**Comment by Michael-Xie** [comment]
> There is no way to do this built into the library. I would suggest simply doubling your grid units.

Thanks for the reply. I have also considered doubling the grid units too for more precise sizing.

One thing that @GeneFTBC pointed out was that the initial values would have decimal values but resizing with the UI would only be in whole increments. A way to get around this is to have an editor that can adjust the values directly - any real numbers. However, when I did that the UI wouldn't update with the new changes. I believe this is because `onLayoutChange` is not triggered when directly adjusting the value. The somewhat hacky solution is to change the key of the `ResponsiveGridLayout` component to create a re-render that would use the updated layout.
