### ISSUE TITLE
how to to set react-grid-placeholder height

### ISSUE THREAD

**Issue by cjl-df** [STRML/react-grid-layout#1194]
i set layout height according the content height 。 but when i drag , i see the placehold height is bigger then the dragelement。 how to fixed it .

**Comment by JamesRamm** [comment]
I'm also interested in this. 
Basically, we want to have a relatively fine row height & high number of columns so a user can finely place their widgets. However we want to have a minimum size of widgets that is somewhat bigger than the row/col increments.
The minimum size we can do, but I couldn't find a way to make the placeholder follow the minimum size of the item...

**Comment by nelsondude** [comment]
In react grid layout component, you can access the place holder in the onDrag handlers. Then you can directly modify its height in rows. I implemented this library making each row 1px tall so that when I needed to modify the placeholder height, setting it to the desired pixel value was straight forward

```
type ItemCallback = (layout: Layout, oldItem: LayoutItem, newItem: LayoutItem,
                     placeholder: LayoutItem, e: MouseEvent, element: HTMLElement) => void;

// Calls when drag starts.
onDragStart: ItemCallback,
// Calls on each drag movement.
onDrag: ItemCallback,
```

so you could write something like `onDrag={(args) => args[3].h = 42}}`

**Comment by JamesRamm** [comment]
@nelsondude thanks
I also found that you could change the (undocumented) `droppingItem` property on the grid. E.g.:

```jsx
<GridLayout isDroppable droppingItem={{i: '__dropping-elem__', h:3, w:4 }} {...props} />
```

It would be nice to know if there is there a recommended way to do this / are their any performance concerns regards one approach vs the other?

**Comment by santoshlokulwar** [comment]
I have one panel in my application which holds widgets which are already designed with its own height and width. I want these widgets to be drag and drop in a grid layout area. But when I drag over a layout, I can not set placeholder height and width for a dragged item. Ideally, it should take its widget height and width. I recommend you to provide an option to give custom height and width for each individual dragged item so that anyone can give different height and width to outside draggable elements.

**Comment by new-furry** [comment]
> i set layout height according the content height 。 but when i drag , i see the placehold height is bigger then the dragelement。 how to fixed it .

Hello ... I am struggling with this one problem...
Could you please anyone share full example code for layout height according the content height?
thank you
