### ISSUE TITLE
Responsive grid order problem

### ISSUE THREAD

**Issue by Arif-un** [STRML/react-grid-layout#1201]
I faced an issue with the grid order.
### Responsive grid order  is on the responsive breakpoint look like this 

![1](https://66.media.tumblr.com/3e7cad757bf89b907f885f0bcfadc5bc/d7d58199979953e0-99/s1280x1920/52ac981c8a92bb3262c552708c97d0acdcc6b948.png)

### I want this order

![2](https://66.media.tumblr.com/e39afb4d75271a4101b55d174c1fc824/7d1f90cad0430917-17/s1280x1920/b7396666f30d2fb8b1a45a4e4b595e4b84b47295.png)

[Codesandbox Demo](https://codesandbox.io/s/resposive-react-grid-layout-1jhm4?file=/src/App.js)
any suggestion?  Thanks.

**Comment by Abdul007Malik** [comment]
I am having the same problem, the problem is due to the first render of the blocks.
The (x,y) coordinated are correct but I think due to the already placed block(of first render/or previous render) on the left it could not transform the current block to their place(means could not override their position) and hence it get pushed to the right of it. So after few rows it (x,y) gets wrong and all get pushed to right.

**Comment by Arif-un** [comment]
hey, I solved in this way  you can also try this [Codesandbox](https://codesandbox.io/s/react-responsive-grid-mxux4)
