### ISSUE TITLE
 Block size with scrollbar

### ISSUE THREAD

**Issue by AndreyZavarin** [STRML/react-grid-layout#1220]
Hello.
There is a problem with the dimensions of the dlocs when a strip strip appears.
Before:
![image](https://user-images.githubusercontent.com/15002874/83510959-8afcc780-a4d6-11ea-927b-df29a1434b36.png)
After:
![image](https://user-images.githubusercontent.com/15002874/83511028-a8ca2c80-a4d6-11ea-950e-c1170c02483b.png)

**Comment by AntonioMendez** [comment]
Hello there!,
I've also found this same issue and I'd like to know if there is any workaround on this, at least. You can reproduce the issue by following these steps in the [documentation demo](https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html):

1. Add enough items until having 2 rows.
2. Resize any item on the second row until forcing vertical scroll in the page.

![overflow](https://user-images.githubusercontent.com/10880610/84366459-c0866c80-abca-11ea-8db1-c800225c44b0.png)

Thanks in advance!...

**Comment by gyto23** [comment]
@AndreyZavarin and @AntonioMendez I found the solution by adding padding to the parent of the ReactGridLayout for example:

```
...
return (
  <div style={{padding: 8}}>
    <ReactGridLayout {...props}>
      {someChilden}
    </ReactGridLayout>
  </div>
)
...
```

This helped me to avoid some issues with resizing on different screens
**NOTE** do not add props to `react-grid-layout` like `margin` and `containerPadding` because its breaks all of the logic on the resize for some reason
