### ISSUE TITLE
Console Warning: findDomNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by piltorious** [STRML/react-grid-layout#1331]
I am using version 1.1.1 with TypeScript in a project using create-react-app. Everything is working properly, this is just an ugly console warning. In my index.tsx I am using <React.StrictMode>

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

![react-warning](https://user-images.githubusercontent.com/23141819/99130622-b3303c80-25c5-11eb-83dc-de386f24668e.JPG)

**Comment by AlOaks** [comment]
Having this same issue. 
Have you found any solution?

**Comment by PatoBeltran** [comment]
Note this package has to remove the findDOMNode in `WidthProvider` and `GridItem` as well as pass a `nodeRef` to `DraggableCore` so that dependency also avoids using `findDOMNode` (https://github.com/STRML/react-draggable/issues/440)

There are two PRs out there with attempts to fix this, but none have been approved by the maintainers (there hasn't been any guidance on what the appropriate fix for this is, maybe something similar to the `nodeRef` in `react-draggable`?

here are links to the PRs:
https://github.com/STRML/react-grid-layout/pull/1318
https://github.com/STRML/react-grid-layout/pull/1092

Hopefully we can get traction on a solution for this soon 😄

**Comment by lanwin** [comment]
Maybe @STRML can say anything about that?

**Comment by christianvari** [comment]
Any news on this?

**Comment by chalettu** [comment]
Any updates on this?

**Comment by piltorious** [comment]
Why do these issues get closed? As far as I'm aware, this issue still exists.

**Comment by STRML** [comment]
Duplicate of #1091

**Comment by STRML** [comment]
Fixed and released in `1.2.3`.
