### ISSUE TITLE
How to change the cursor while drag and drop?

### ISSUE THREAD

**Issue by WaqqarSuleman** [STRML/react-grid-layout#1384]
How to change the cursor while drag and drop?

**Comment by Waqqars987** [comment]
Found a work around using CSS pseudo selectors.

**Comment by TheLox95** [comment]
> Found a work around using CSS pseudo selectors.

And what are the selectors that allow you to do that?

**Comment by kerorojason** [comment]
Hi @Waqqars987, I would also like to know the selector you use to alter the `cursor: copy` when dragging element, thanks!

**Comment by nebrelbug** [comment]
You can use the "active" pseudo selector. Ex. in Tailwind I use `cursor-grab active:cursor-grabbing`

**Comment by 15960331** [comment]
I think using active pseudo selector doesnt work as people here expect because it only works when an item is clicked but not when an item is dragged.

I looked at the RGL codes and looked up on the internet, ended up finding workarounds that only work on certain browsers.

https://stackoverflow.com/questions/10119514/html5-drag-drop-change-icon-cursor-while-dragging
