### ISSUE TITLE
rowHeight calculate error! 

### ISSUE THREAD

**Issue by senro** [STRML/react-grid-layout#233]
```
var layouts = {
            lg: [
                {i: '1', x: 0, y: 0, w: 1, h: 2},
                {i: '2', x: 1, y: 0, w: 1, h: 1},
                {i: '3', x: 2, y: 0, w: 1, h: 1}
            ]
        };
        return (
            <ResponsiveReactGridLayout className="layout" rowHeight={10} margin={[10,10]} layouts={layouts}
                breakpoints={{lg: 1200}}
                cols={{lg: 12}}>
                <div className="rcBlock" key={"1"} style={{height:20}}>1</div>
                <div className="rcBlock" key={"2"}>2</div>
                <div className="rcBlock" key={"3"}>3</div>
            </ResponsiveReactGridLayout>
        )
```

Hi, i have a question, i run this code, i thought the (div of key=1)'s height should be 20px, but whatever i resize the (div of key=1), the (div of key=1)'s height cannot be set to 20px ,the mini size is 30px, even i set the height style, the (div of key=1) cannot be set to 20px, why????can anybody help me? thanks very much!!!!!!

**Comment by simianhacker** [comment]
Margins are essentially broken because in the code there is no way to calculate how much margin to add to the `top` attribute. For example if you have three rows of `h:5` grid items. How many margins should you use to calculate the `top` for the last row? The answer is 2 for the next row (4th row) it would need to be 3 (adding one per additional row). This gets more complicated when you add columns into the mix. But in the code there is no way to determine which row the grid item is because it doesn't know the size of the previous rows and how many times margin has been added. I don't see this being fixed without a refactor. My advice is to not use margins.

**Comment by STRML** [comment]
Why are you setting your own `height` or `top`? That is exactly what the library manages for you.

**Comment by simianhacker** [comment]
I'm not... but the library doesn't calculate the container height correctly... Create a grid with the `margin` set to `[10,10]' and the `rowHeight` set to `10`. Then create an item where the `h` is set to `5`. Inspect the `height`  of the actual element, it will be set to `90px`.

**Comment by STRML** [comment]
Yes, that is intentional, otherwise you would end up with a staggered grid. Try adding a few items with `h:1-4` in the same row in your grid. Heights must also then span the margin.

Alternatively, rowHeight could be deducted by the margin (so `rowHeight:15` and `margin: `[5, 5]` results in an actual child height of `10`, but that's also unintuitive.

Consider in your solution what happens if you have a child with a height of `1`.

**Comment by simianhacker** [comment]
I also set the minH to 5... I guess I forgot to add that... Essentially, I want users to be able to adjust their layout by 10px but not create elements smaller then 50px. 

Other then that one thing... thank you for this library :D

**Comment by genton** [comment]
Hello STRML,
First thank you for sharing this really good lib!
Could you develop a bit further on your last comment?
After experimenting a bit, here is what I understand:
an item with h = 1 will have a height of rowHeight
an item with h = n > 1 will have a height of rowHeight + (n-1) * (rowHeight + marginHeight)

this matches simianhacker's example where n = 5, rowHeight = 10, marginHeight = 10.
He gets a final height of 10 + 4 * (10 + 10) = 90 px.

So my question is: how could this be an intentional design? h = 1 and h > 1 have a different step size.
I understand that we have to make sure not to have staggered grids, but why isn't it possible to have a direct linear correspondance between the actual item height and  its h layout property?

I am asking this because I want to use the evolving h and w layout attributes of my layout to feed my custom react components their new sizes and rerender them.

**Comment by STRML** [comment]
Please see above. There is no other way it could be: height is equal to `h * rowHeight + (h - 1) * margin`. It is intentional design such that the grid lines up, and other grid libraries work th esame way.

**Comment by abelkbil** [comment]
Thanks @STRML ,

![image](https://user-images.githubusercontent.com/1478274/35548595-9000d090-05a6-11e8-95b1-3ff22ddab4f9.png)

I am not able get a preferred height, Is it because of the above mentioned height calculation. Any possibility as seen in the demo gif.  I get 18 breakpoints in width but not in height.

`items: this.state.items.concat({
            i: widgetId,
            x: (this.state.items.length * 2) % (this.state.cols || 12),
            y: Infinity, // puts it at the bottom
            w: 1,
            h: 1,
        }),`

`<ResponsiveReactGridLayout
                    breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
                    cols={{lg: 18, md: 10, sm: 6, xs: 4, xxs: 2}}
                    autoSize={false}
                    onLayoutChange={this.onLayoutChange}
                    onBreakpointChange={this.onBreakpointChange}
                    containerPadding={[0,0]}
                    margin={[2,2]}
                    isResizable={ this.state.isGridEditable }
                    isDraggable= { this.state.isGridEditable }
                    {...this.props}
                >
                {_.map(this.state.items, el => this.createElement(el))}
                </ResponsiveReactGridLayout>`

Thanks you all for consideration, @simianhacker any input ?

**Comment by abelkbil** [comment]
@STRML and @simianhacker ,
Setting rowHeight: 100 give me the height step, Now it will increase every 100px.
Thanks

**Comment by DanielGriffiths1182** [comment]
I was able to fit the boxes to the viewport height like so:

`const h = viewPortHeight / rowHeight - viewPortOffset / rowHeight`

```
h = box height unit
rowHeight = "defined PROP for rowHeight"
viewPortHeight = "window height"
viewPortOffset = "nav bar, footer, etc."
```

with a vertical seperating margin of 0, and (irrelevant) a lateral margin of 10

**Comment by tonix-tuft** [comment]
@STRML It is a bit difficult for me to understand why `react-grid-layout` computes the height of a grid item this way, and I think the same goes for other people who first approach to this library. Could you please explain why e.g. the height of a grid item with `h: 3` when `rowHeight={120}` isn't just `120 * 3 = 360px`? Anyway, thank you for this library! :)

**Comment by STRML** [comment]
Because of margin @tonix-tuft. Otherwise you would have a ragged grid. Rather than explain again, please re-read the above notes.

**Comment by JohnGrisham** [comment]
> Please see above. There is no other way it could be: height is equal to `h * rowHeight + (h - 1) * margin`. It is intentional design such that the grid lines up, and other grid libraries work the same way.

If you're like me and you know the actual height in px but you need the calculated h value for setting an item to the height equivalent of the full grid you can use.

h = (y + m) / (r + m)

**Comment by justdvl** [comment]
`height is equal to h * rowHeight + (h - 1) * margin`
This should be written in documentation to save debugging time.

**Comment by costea93** [comment]
hey guys, i don't really understand how this height works. For example: i have 3 rows, and i want for first row to set 130px height, for second 138px, and for third 230px... How can this be done? Thanks

**Comment by STRML** [comment]
You can't. It's a grid, in order for items to be swappable between rows, all the rows need to be the same height.

**Comment by jadghadry** [comment]
> > Please see above. There is no other way it could be: height is equal to `h * rowHeight + (h - 1) * margin`. It is intentional design such that the grid lines up, and other grid libraries work the same way.
> 
> If you're like me and you know the actual height in px but you need the calculated h value for setting an item to the height equivalent of the full grid you can use.
> 
> h = (y + m) / (r + m)
> 
> with y being the height of the grid in px.

@JohnGrisham You're correct that the formula needs to be adjusted to account for margins. Given `y` as the height of the grid in pixels, the formula for calculating the grid item height `h` should be:

    h = (y + m) / (r + m)

Where `y` is the height of the grid in pixels, `m` is the vertical margin, and `r` is the row height.

However, the correct formula should consider subtracting the two outer margins as well. Therefore, the new formula becomes

    h = (y -2m + m) / (r + m) = (y - m) / (r + m)

This formula subtracts the vertical margin `m` from the height of the grid `y` to account for the outer margins, and then divides the result by the sum of the row height `r` and the vertical margin `m`.

Using this corrected formula, you can calculate the grid item height `h` to set an item to the height equivalent of the full grid.
