### ISSUE TITLE
Upgraded to latest RGL, now losing fields from grid item object

### ISSUE THREAD

**Issue by JosefWN** [STRML/react-grid-layout#275]
Hello, I just upgraded from 0.9.x. According to the documentation, the following fields can be set for each item:

``` javascript
{

  // A string corresponding to the component key
  i: string,

  // These are all in grid units, not pixels
  x: number,
  y: number,
  w: number,
  h: number,
  minW: ?number = 0,
  maxW: ?number = Infinity,
  minH: ?number = 0,
  maxH: ?number = Infinity,

  // If true, equal to `isDraggable: false, isResizable: false`.
  static: ?boolean = false,
  // If false, will not be draggable. Overrides `static`.
  isDraggable: ?boolean = true,
  // If false, will not be resizable. Overrides `static`.
  isResizable: ?boolean = true
}
```

I have previously created my own custom fields. Then I set _grid={el} for each item. The problem now is that as soon as I have loaded my items into the grid, all of my custom fields are lost, and the items appear with only the fields listed above. What can I do to remedy that?

**Comment by Puffton** [comment]
A side effect of using cloneLayoutItem. It would be cool with a smarter method for deep cloning. For example JSON serialization and deserialization: http://stackoverflow.com/questions/122102/what-is-the-most-efficient-way-to-clone-an-object

Surely not as quick, but with small objects, the performance difference will likely be negligible, and it would be much more flexible to use.

**Comment by STRML** [comment]
Why not just assign the props to the children directly?

```js
<ReactGridLayout ....>
  <div foo="bar" _grid={el} />
</ReactGridLayout>
```

**Comment by Puffton** [comment]
I do, but as soon as something changes in the grid, they come back onLayoutChange, without those properties?

**Comment by Puffton** [comment]
Oh, I got what you meant now. Well, the biggest problem is I have a lot of data in the DB which is already following this format (each item has its own props and my custom props). I would have to make a compatibility layer for load/save operations then, and re-write the code to use two separate lists of fields instead of just one. Feels pretty clunky.

**Comment by STRML** [comment]
Yeah, the issue is that the `_grid` property wasn't meant to be used this way. It was only by accident that you could attach your own custom properties. The intention is that the `Layout` objects remain represented by a single hidden class so the code remains fast. Are you expecting them to come back on the `onLayoutChange` callback?

**Comment by Puffton** [comment]
Yeah, that's what I plug into the DB when the user persists the grid.

Is there any downside to my suggestion?

**Comment by STRML** [comment]
As in, a `payload` prop?

**Comment by STRML** [comment]
To be honest the whole thing feels a bit hacky to me, you could just merge the new layout with the existing one on save rather than have the lib provide first-class support for databags inside the layout. I don't think it is really in the scope of this module to provide that.

**Comment by Puffton** [comment]
Not necessarily a payload, but my implementation of cloneLayoutItem. Less maintenance for you, easier use for me?

**Comment by STRML** [comment]
My issue is that this is a really hot function. Even iterating through own properties will be measurably slower.

However, I exposed `utils` in the last release or so. You could just assign to `utils.cloneLayoutItem` and override it yourself.

**Comment by Puffton** [comment]
In which scope is utils defined? This is how I'm including RGL with Browserify:

```javascript
global.WidthProvider = require('react-grid-layout').WidthProvider;
global.ResponsiveReactGridLayout = WidthProvider(require('react-grid-layout').Responsive);
```

**Comment by STRML** [comment]
`const rglUtils = require('react-grid-layout').utils`

**Comment by Puffton** [comment]
I can set it just fine, but it doesn't seem to be used:

```javascript
  global.RGLUtils = require('react-grid-layout').utils;
```

```javascript
  RGLUtils.cloneLayoutItem = function (layoutItem) {
    var newObj = {};
    for (var key in layoutItem) {
      if (layoutItem.hasOwnProperty(key)) {
        newObj[key] = layoutItem[key];
      }
    }
    return newObj;
  }
```

**Comment by eMerzh** [comment]
Yeah doesn't seems to work here either with the latest release ... is there a way to achieve this ?

i have the same exact problem... i've added like the "widgetType" in my layout and expect to see it back as property of the layout given by onLayoutChange ...

i'm stuck to react 15.1 because of that

**Comment by Puffton** [comment]
@eMerzh: Every time I download a new version of RGL I patch it manually. Not ideal, but it works...

**Comment by STRML** [comment]
Yeah, so this appears to be an issue with `import` statements not allowing us to properly override these libs.

I understand this stuff isn't ideal. I really want to add a lot more extension points to the library because it's obvious the provided ones simply aren't enough. In addition there will be only one way to provide grid data (not both `layout` and `data-grid`). Please see https://github.com/STRML/react-grid-layout/issues/346

**Comment by Puffton** [comment]
Hi @STRML! Is this on the roadmap?

**Comment by STRML** [comment]
Sort of - I just haven't had the time to expand out this library due to time commitments at my day job. Would love if someone were willing to lead the API design effort.

**Comment by Puffton** [comment]
Thanks for quick freedback, just saw the reference to the megathread as well.

**Comment by digz6666** [comment]
Its from 2019 but still affecting current version. Should I override as mentioned by @JosefWN ?
