### ISSUE TITLE
Unknown prop `_grid` on <div> tag

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#283]
With the latest version of React and RRGL I'm getting: Unknown prop `_grid` on &lt;div&gt; tag. Remove this prop from the element.

**Comment by rldotai** [comment]
That is, I believe, due to a change in React in version 15.2 or 15.1 ([see CHANGELOG.md](https://github.com/facebook/react/blob/master/CHANGELOG.md)).

It only complains at the moment, but there is presumably a way of fixing it-- I just don't know enough about React to say with certainty what a better pattern would be.

**Comment by STRML** [comment]
I think we're going to have to define `<GridItem>` for this to work. The current implementation is a bit of a hack (it clones the element and lifts the properties).

**Comment by maiduchuy** [comment]
The way I see it, we can either move from `<div>` to `<GridItem>` or use `data-*` (in this case, `data-grid`) instead of `_grid`

**Comment by MrCsabaToth** [comment]
https://stackoverflow.com/questions/38368349/react-grid-layout-example-unknown-prop-grid-on-div-tag changing it to `data-grid` should simply work or should I introduce a `GridItem` component? The `h` and `w` doesn't seem to be picked up.
