### ISSUE TITLE
max number of rows?

### ISSUE THREAD

**Issue by eelkeh** [STRML/react-grid-layout#30]
Is there a way to set a maximum number of rows?
Something like: 

``` javascript
{ cols:4, maxRows: 10 }
```

Is something like this possible? Any pointers would be great!

**Comment by STRML** [comment]
Sorry, this is not yet possible. You could likely implement it yourself using the `onDragStop` and `onResizeStop` handlers.

**Comment by NSinopoli** [comment]
+1. @STRML I'd be more than happy to implement it myself if you could point out what would need adjusting... I took a look at `mixinResizable` in `lib/GridItem.jsx`, but it seems we'd have to restrict more than just the height component of `maxConstraints`. (Imagine a layout with `verticalCompact` set to false and the smallest possible `GridItem` being dragged around.)

**Comment by ngotchac** [comment]
That would be great! :)

**Comment by ruanmer** [comment]
+1

**Comment by ruanmer** [comment]
+1

**Comment by STRML** [comment]
`maxRows` is implemented, but somewhat buggy. It is possible to push an item beyond the maxRows as the compaction algorithm is not tuned to move elements sideways.

**Comment by jlndk** [comment]
+1

**Comment by kutyepov** [comment]
+1

**Comment by STRML** [comment]
Please don't spam us with `+1` comments. Use the emoji, or, better yet, submit a PR.

**Comment by antoine35** [comment]
Has anyone found a solution to force the maximum number of lines ? Thanks

**Comment by SomethingSexy** [comment]
If props.onDrag or props.onDragStop returned whether it could be dropped help with this situation?  I am looking for something similar but trying to figure out I can implement it with the given props now.

**Comment by ryancwalsh** [comment]
Thank you so much for this amazing library. I'm very impressed.

I would definitely love if we had `maxRows` and `maxCols` props that worked well. (E.g. I'd like to have a 3x3 grid of tiles that can be dragged around only within that 3x3 grid.)

From the comments on this issue and the linked one, it seems like the callbacks that would be necessary in order to implement `maxRows` and `maxCols` props don't exist either.

As I start to use react-grid-layout, I will explore, and I'll let you know if I come up with anything.

**Comment by ryancwalsh** [comment]
@adnan-smlatic Nope.
