### ISSUE TITLE
Separate rowHeight for each item? How to fit to screen height

### ISSUE THREAD

**Issue by hepiyellow** [STRML/react-grid-layout#329]
I am trying to figure out how to fit the grid exactly to the screen height (no scrolling).
Lets take a simple example were there are only 2 items, and the screen height is 401.
Well, 401 does not divide well by 2, so I can't use rowHeight=200.
(This is with margin=0)
- One approach to solve this might result in having one item's height 200 and the other 201
- Another approach is to have both items height=200, and have a margin of 1px.

I found a [similar issue](https://github.com/STRML/react-grid-layout/issues/242) in which it was suggested to use rowHeight=1, and use the h argument for controlling the height in pixels. but that works only if the margin is 0.

Is this solvable with react-grid-layout?
Any suggestions?

Thanks,
Erez

**Comment by jackychow** [comment]
I am trying to achieve the same thing. 
Instead of trying to be precise, I am just going the "make-believe" route. Set overflow hidden on the container of the gridlayout. And just calculate the rowHeight everytime the screen resizes with a Math.ceil. E.g. if screen height is 400 and I am using a 12 rows grid, my row height is Math.ceil(400.0/12) so 34. Yes, the total height ends up at 408 so 8 pixels are hidden on the bottom, but visually it works pretty well most of the time for me as the difference is less than 5 pixels.

To the extreme, I think there are number CSS positioning tricks that you can use making the final result more "believable" to be precise such as shifting the outer container etc.
