### ISSUE TITLE
`onDragStop` is called with incorrect `newItem`

### ISSUE THREAD

**Issue by cp** [STRML/react-grid-layout#345]
In my usage it seems that `onDragStop` is actually called with incorrect data when the item is dropped. I would expect the `newItem` argument to essentially have the dimensions+position of the "placeholder" underneath the dragged item, but it instead has the exact position of where the dragged item was when it was dropped.

Though you can hardly visually discern the placeholder, dropping the currently dragged item (below) will place it with a `y` value of 1 less than the user would expect:

![onDragStop](https://cloud.githubusercontent.com/assets/1715618/18421084/fb010658-7835-11e6-8b2f-bae02fa64d24.png)

This issue only manifests itself when `static === false`, since otherwise vertical packing will hide it.

This seems like a fairly large issue, so I want to confirm it's not by design. I'd be happy to submit a PR to resolve it, but wanted to get some feedback here first.

Would be happy to throw an example up into a gist if my explanation isn't sufficient.

**Comment by STRML** [comment]
I can't really see in the photo - might be the contrast on my screen - but just so I'm understanding this correctly; you want `onDragStop` to tell you where the item ends up after it is compacted, not before it is compacted.

It is intentional to callback `onDragStop` with where the item was dropped, because I figured that exact information may be useful to you. 

You can get around this with the following:

* Record the `i` of the item `onDragStop`.
* Correlate it with the matching item from `onLayoutChange` and use that position instead.

**Comment by cp** [comment]
Okay, I'll try that out. To clarify, my expectation was that the dropped item would just inherit the position of the "placeholder" created while dragging it. Since the point of the placeholder (I believe) is to show the user where the item will go when it's dropped. Not necessarily about it being compacted. Does that make sense?

**Comment by STRML** [comment]
Well, what really happens is that it is dropped where you place it, then immediately compacted. The same is done for the placeholder because it would be misleading otherwise.

I understand the confusion - I am thinking of how to make this less surprising while still making pre-compaction data available. Perhaps naming is really the issue.

**Comment by cp** [comment]
Ah! That makes a lot of sense now. I disabled compaction and tried it out... I totally get it.

Trying to think of ideas too... maybe only passing pre-compacted data when `verticalCompact === false`? Is there a case when someone would need pre-compacted data when compaction is disabled?

Or splitting it into two arguments on the callback, one for the compacted layout and the other for a pre-compacted one?

**Comment by STRML** [comment]
That's a possibility re: two callbacks.

As for someone needing pre-compacted data, in that case the data in `onLayoutChange` (which has the whole layout, and is useful for that reason) will be the same for that item as it is on `onDragStop`. Which is how it should work most intuitively. The only reason `onDragStop` sends "stale" data is so that you at least have it somehow if you need it.

**Comment by cp** [comment]
Makes sense. Another possible option could just be updating the documentation: specifying the ways to access both the compacted and pre-compacted layout.

**Comment by kachkaev** [comment]
I also face the issue of inconsistency between the location of the placeholder and the layout I get in `onDragStop` when `compactVertical` is `true`. @cp, have you found a way to get the actual (not stale) location of the item?

**Comment by STRML** [comment]
@kachkaev See the workaround in https://github.com/STRML/react-grid-layout/issues/345#issuecomment-246214707
