### ISSUE TITLE
autoSize not working completely?

### ISSUE THREAD

**Issue by duranb** [STRML/react-grid-layout#35]
I'm having an issue with the autoSize flag.  Each grid item seems to just take the **h** specified blindly regardless if this flag is set to true.  The weird thing is that the resize handle is in the correct position as if it knows how tall the content is.
![capture](https://cloud.githubusercontent.com/assets/5290214/6497522/c8675154-c295-11e4-8225-6212225f409a.PNG)

Both of the grid items have an **h** of 1.
```
    getDefaultProps: function() {
        return {
            autoSize: true,
            isResizable: true,
            useCSSTransforms: true,
            draggableHandle: "div.draggable",
            cols: 12,
            rowHeight: 50
        };
    },
    render: function() {
       <ReactGridLayout className="layout" {...this.props}>
                <div key="test0">
                    <div className="draggable">TEST</div>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                </div>
                <div key="test1">
                    <div className="draggable">TEST</div>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                    <p>TESTTEST</p>
                </div>
       </ReactGridLayout>
    }
```
Am I doing something incorrectly?

**Comment by STRML** [comment]
Hi @duranb ,

The autoSize flag is for the entire Grid Layout container, not the individual grid items.

At this time I do not support autosizing of grid items as it requires reading from the DOM to figure out an item's dimensions, and doesn't give with the integral grid system as it stands.

In order for autosizing to work, React-Grid-Layout would need to be reconfigured to use a pixel grid instead of a unit grid. Row/column sizes could still be defined in integer units (say, 1 column is 60px wide) but the underlying grid would have to be represented in pixels. Then, any grid item with automatic width or height would have to read from the DOM to understand the size of its content and adjust the layout proportionally.

IMO, if you need this kind of functionality, it may be best to use one of the many jQuery grid layouts. This project is intended to be pure, without any direct DOM manipulation, and renderable server-side without checksum errors (although I believe there is a pending issue on that). Such a change would really be a major departure from what this project is about.

**Comment by duranb** [comment]
Fair enough.  How should I go about fixing the resize handle? Does the content have to be positioned absolutely?

**Comment by STRML** [comment]
If the content fits, the resize handle should be placed appropriately. Otherwise, try adding `overflow:hidden` using CSS on the grid items.
