### ISSUE TITLE
Accessing isMounted inside its render()

### ISSUE THREAD

**Issue by kibs** [STRML/react-grid-layout#38]
The console gives me a warning that "ReactGridLayout is accessing isMounted inside its render()"
I know this doesn't affect the grid, but maybe in a later React version, this will become a real issue.

Only tested using React 0.13

**Comment by STRML** [comment]
Yeah, it appears they may be removing `isMounted()` - best I can tell is
that they say it won't work inside ES6 classes, but I haven't gotten any
coherent reason as to why, or why it would be removed.

We use it to switch to CSS transforms after mounting which have better
performance, but it is not possible to do this effectively on the
server-side. This is because CSS transforms don't support percentage
offsets - while `top` and `left` percentage values are equal to their
container ("move this element down 40% of its container's height"),
percentages with CSS transforms are relative to themselves ("move this
element down 40% of its own height"), which is not useful.

Since we don't know the browser's width on the server this leads to
breakage on initial load until the JS has time to run. I didn't want to
turn this into yet another app that shows a "loading..." screen, I want
the layout to be correct when starting, so that's why we use this. It's
not enough to simply check `process.browser`, because otherwise the
layout will fail the checksum.

**Comment by kibs** [comment]
Ahh makes sense, didn't really think about serverside. Didn't really think you didn't know, as you probably also are using the console :wink: but could'nt find an issue, so I thought I would ask.

Thank you for the detailed answer, and thank you for this really great project!
