### ISSUE TITLE
[Question] Duplicate child key found! This will cause problems in ReactGridLayout.

### ISSUE THREAD

**Issue by subhamagr** [STRML/react-grid-layout#481]
ReactGridLayout is automatically creating duplicate keys. 

```javascript
componentWillReceiveProps (nextProps) {
  if (nextProps.fetched && !this.props.fetched) {
      const layout = _.map(nextProps.regions, region => {
        return {
          x: toInteger(region.left),
          y: toInteger(region.top),
          h: 2,
          w: 1,
          maxH: 40,
          static: true,
          isDraggable: false,
          isResizable: false,
          i: toString(region.region_id)
        }
      });
     console.log('my layout', { layout: { lg: layout, md: layout }});
     this.setState({ layout: { lg: layout, md: layout }} );
  }
}
```
and i have a onLayoutChange callback

```javascript
onLayoutChange (layout, layouts) {
    console.log('onLayoutChange', layout, layouts);
}
```

and in my render function

```javascript
render() {
   return (
       <ResponsiveReactGridLayout
            className="layout" rowHeight={40}
            breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
            cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}
            onLayoutChange={this.onLayoutChange} layouts={this.state.layout}
            onBreakpointChange={this.onBreakpointChange}
            verticalCompact={false} isDraggable={shouldBeDraggable} isResizable={false}
       >
       {myRegions}
     </ResponsiveReactGridLayout>
  )
}
```
Where am I doing wrong?
![image](https://cloud.githubusercontent.com/assets/7915409/22851924/baf41d22-f056-11e6-8522-55fb2054389c.png)

**Comment by STRML** [comment]
It is likely your region ids are not unique.

On Feb 11, 2017 2:16 PM, "Subham Agarwal" <notifications@github.com> wrote:

ReactGridLayout is automatically creating duplicate keys.

componentWillReceiveProps (nextProps) {
  if (nextProps.fetched && !this.props.fetched) {
      const layout = _.map(nextProps.regions, region => {
        return {
          x: toInteger(region.left),
          y: toInteger(region.top),
          h: 2,
          w: 1,
          maxH: 40,
          static: true,
          isDraggable: false,
          isResizable: false,
          i: toString(region.region_id)
        }
      });
     console.log('my layout', { layout: { lg: layout, md: layout }});
     this.setState({ layout: { lg: layout, md: layout }} );
  }
}

and i have a onLaoutChange callback

onLayoutChange (layout, layouts) {
    console.log('onLayoutChange', layout, layouts);
}

and in my render function

render() {
   return (
       <ResponsiveReactGridLayout
            className="layout" rowHeight={40}
            breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
            cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}
            onLayoutChange={this.onLayoutChange} layouts={this.state.layout}
            onBreakpointChange={this.onBreakpointChange}
            verticalCompact={false} isDraggable={shouldBeDraggable}
isResizable={false}
       >
       {myRegions}
     </ResponsiveReactGridLayout>
  )
}

Where am I doing wrong?
[image: image]
<https://cloud.githubusercontent.com/assets/7915409/22851924/baf41d22-f056-11e6-8522-55fb2054389c.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/STRML/react-grid-layout/issues/481>, or mute the thread

**Comment by subhamagr** [comment]
I have checked them. They are unique. Why is it that onLayoutChange is called with a list of 25 objects when I have provided only 5?

**Comment by eric-burel** [comment]
Hi, I think the error message should definitely print the duplicated key for debugging purposes.
