### ISSUE TITLE
Include dist in npm

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#58]
Could the dist-dir be included in npm? I find it very handy to manage my dependencies with npm, but only plan on using the minified js.

**Comment by STRML** [comment]
Are you not using a build tool like webpack or browserify? I am not sure
how you would use npm modules otherwise.

In general it is not usual to include minified source in npm; it bloats
the package and is practically never used.

I don't intend to add minified source to the package. If you want to
work around this, add the latest git revision to your package.json
instead. When npm pulls from git the dist dir will be there.

**Comment by Puffton** [comment]
Was trying to keep the project/workspace dependencies to a minimum, but gave up and went with browserify and minifyify.
