### ISSUE TITLE
this.props.onLayoutChange is not a function

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#60]
Sorry if I'm doing something obviously wrong, I'm new to react and this component.

I used your example in 6-dynamic-add-remove.jsx. On line 73 (this.props.onLayoutChange) I get an error: "this.props.onLayoutChange is not a function.". If I comment the line out, I can use the code (but there are some issues with resizing). I render in a similar fashion to you:

document.addEventListener('DOMContentLoaded', function (event) {
	var contentDiv = document.getElementById('content');
	var gridProps = window.gridProps || {};
	React.render(React.createElement(AddRemoveLayout, gridProps), contentDiv);
});

Differences: I'm not using your hooks, and I noticed that you are using a specific requires for "PureRenderMixin" whereas requiring React and using React.PureRenderMixin should also work?

You wouldn't happen to know if this is a common pitfall?

**Comment by STRML** [comment]
I don't believe `React.PureRenderMixin` is actually defined - is that a `0.13` change? I don't see it locally.

Anyway, yes, just remove that line. It is there because that component, in the demo, updates the little text box that shows the internal state of each layout item. It is safe to remove. See [how it is initialized](https://github.com/STRML/react-grid-layout/blob/master/test/test-hook.jsx#L42).

**Comment by Puffton** [comment]
I must have seen it somewhere, but it was likely an unofficial source, so I just went with: 
var PureRenderMixin = require('react/addons').addons.PureRenderMixin;

Removed the line as per your suggestion and everything seems to be working smoothly, thanks!
