### ISSUE TITLE
Why 'key' and 'i' used as different keywords for same task?

### ISSUE THREAD

**Issue by lugrugzo** [STRML/react-grid-layout#627]
Also, why even 'key' keyword used to identify? 

When passing layouts we are using 'i'. I found it confusing because couldn't it be good if its a common keyword for both like 'viewId'?

**Comment by STRML** [comment]
Key is especially important because I assume items can be added and removed from the layout at any time. If it were just done by index in the array it could be quite confusing to work with.

I agree that `key` would have been a better name in the layout arrays than `i`, but changing it now would be a breaking change.

`viewId` is a non-starter because children can be dom elements and that would be an invalid attribute, so I'd have to strip it (clone) the el before rendering it, which is not terrible but unneeded processing.

**Comment by lugrugzo** [comment]
Thanks for your explanation.
