### ISSUE TITLE
Horizontal compacting

### ISSUE THREAD

**Issue by TheoRyley** [STRML/react-grid-layout#66]
When a responsive grid is resized its items aren't compacted horizontally leaving empty space on the left.

![example1](https://cloud.githubusercontent.com/assets/12641659/7894535/21022aaa-0639-11e5-98bf-63e727fd699e.png)
![example2](https://cloud.githubusercontent.com/assets/12641659/7894538/2e207e9e-0639-11e5-99b4-c1808529d96d.png)

**Comment by doeg** [comment]
I'm seeing this as well. Not sure if it's intentional or a bug.

**Comment by STRML** [comment]
This is more or less intentional, but only because I simply haven't defined rules for where these items should go when they are squeezed out.

See [where a new layout is generated](https://github.com/STRML/react-grid-layout/blob/master/lib/responsiveUtils.js#L52) for somewhere to start if you want to mess with this issue.

Just an FYI, there are some dragging issues in `master` that you won't see in the demos; nothing to worry about, I'm working on a refactor of `<Draggable>` that will fix it.

**Comment by doeg** [comment]
@STRML Awesome, thanks for the code pointer. I'd love to play around with it. :) If I come up with anything worthwhile, I can send a PR your way.

Thanks so much for writing such a great library!

**Comment by cmelion** [comment]
I created a quick and dirty fork that replaces the vertical compacting with Horizontal compacting and some additional behavior required for a project I'm working on.  Not sure if the examples will work without modification, but will try and fix if there is any interest.  At some point in time I'll attempt to make the compaction rules configurable.

https://github.com/cmelion/react-grid-layout

**Comment by STRML** [comment]
The branch [horizontalCompact](https://github.com/STRML/react-grid-layout/tree/horizontalCompact) makes this configurable via a new prop, `compactType`, which deprecates `verticalCompact`. Options are `'horizontal'`, `'vertical'`, or `null`.

Behavior seems good so far, would appreciate anyone who's willing to test it.

Also thinking about expanding this to `top/bottom/left/right`, with `top` being the current behavior. `bottom` would be tricky without a fixed height though, and RGL will do undefined things with fixed heights.

**Comment by AlanBreck** [comment]
Not sure what I'm doing wrong, but I'm attempting to use the horizontalCompact branch, but running into errors when attempting to install dependencies and build. When running `npm install`, I get the following output: https://gist.github.com/AlanBreck/2ccb8b7052b46534d24ca7690048ff77#file-gistfile1-txt

The errors start on line 65: https://gist.github.com/AlanBreck/2ccb8b7052b46534d24ca7690048ff77#file-gistfile1-txt-L65

Any thoughts?

**Comment by uneart** [comment]
I'm also interested in using horizontal instead of vertical compacting. How can I install this branch using npm?

**Comment by rorz** [comment]
Is there a reason why this was dropped? I was checking out the branch and it seems to have been written in a way that was intended to supersede _vertical-only_. Now it's gone a bit stale since its last commit was 9 months ago and this is a well-maintained project.

I'm interested in using both horizontal and vertical compacting in tandem, and wouldn't mind doing the groundwork (using the current branch as a primer) if @STRML is open to the idea?

I'm new to React, however, and would probably need some co-contributors if the demand is still there.

**Comment by agaurav** [comment]
@rorz @STRML I will be very much willing to help out as well.

**Comment by victor5114** [comment]
@STRML @agaurav I'm also interested in improving the horizontal compacting feature.

**Comment by TrySound** [comment]
I guess it's fixed.

**Comment by Muneebwasikhan** [comment]
Not fixed yet?? can anyone help if know the solutio?

**Comment by genie4viz** [comment]
I am not sure this way can be good solution.
But we can change compactType by using useState(hook).
const [compactType, setCompactType] = useState('vertical');
<ResponsiveGridLayout
...
compactType={compactType}
/>
const onRemoveItem = () => {
   setTimeout(() => {
      setCompactType((prev) =>
        prev === "vertical" ? "horizontal" : "vertical"
      );
    }, 300);
}
This works for me :)
