### ISSUE TITLE
[Question] Can I compile this entire library into one file?

### ISSUE THREAD

**Issue by nebrelbug** [STRML/react-grid-layout#687]
I am building a static site, but I can't use npm or node_modules. I love this package, and would like to include it in my site. Is there a way I could use the entire library in just 1 or 2 JS and CSS files? Thank you so much!

More Info: I'm building a Chrome extension, so size is essential.

**Comment by nebrelbug** [comment]
I saw the file in the `dist` folder, but it's not included in the NPM package (otherwise I could access it via unpkg) and I get an error when I try to load it from Github. Here's a link to a Codepen: [https://codepen.io/nebrelbug/pen/xpxomN](https://codepen.io/nebrelbug/pen/xpxomN). Thanks!

**Comment by nebrelbug** [comment]
Never mind, I found a helpful CodePen. Thanks!

**Comment by oclyke** [comment]
@nebrelbug Any chance you still know where to find that example? I have been struggling for quite a while trying to use react-grid-layout with a CDN link.

Moreover is there a standard way of doing this? I'm already using React and styled-components via cdn links but those scripts present a global variable into ```window``` that can be used intuitively (e.g. ```const var = window.styled.div```. With ```react-grid-layout``` I can see a global function called ```ReactGridLayout``` but its usage is beyond me. I tried using ```require.js``` but got lost in the weeds quickly.

Thanks!

**Comment by nebrelbug** [comment]
@oclyke here's my Codepen, which I updated to work: https://codepen.io/nebrelbug/pen/xpxomN

Check "Javascript" under "Settings"

**Comment by oclyke** [comment]
I used that Pen's code in my own context and it worked well. One more question if I may... How would I replicate [this example](https://github.com/STRML/react-grid-layout/blob/master/test/examples/0-showcase.jsx) using a CDN? 

``` js
import React from "react";
import _ from "lodash";
import { Responsive, WidthProvider } from "react-grid-layout";
const ResponsiveReactGridLayout = WidthProvider(Responsive);
...
class ShowcaseLayout extends React.Component {
  render() {
    <ResponsiveReactGridLayout
    ...
    </ResponsiveReactGridLayout>
  }
}
```

Since apparently the ```ReactGridLayout``` component is made available without any special action I'm wondering how to access the ```WidthProvider``` and ```Responsive``` exports of the library (framework? module? I guess I don't know the right term in this context). 

I've searched the members of the ```window``` object but only found ```ReactGridLayout``` and can't imagine how I would get the others out of it since it seems to be a genuine React component. 

Is the responsive functionality of react-grid-layout available without using node modules?

Thanks a lot for your help
