### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by brenoc** [STRML/react-grid-layout#76]
I would like to know if this component works on IE8.

Does anyone know if it does?

**Comment by STRML** [comment]
It likely does not. There are problems with `<Draggable>` and `<Resizable>` even in newer IE versions. I am working on a fix for them but it involves a more major rewrite.

**Comment by brenoc** [comment]
@STRML thanks. Btw, great job, awesome component!

I think this info about the browser compatibility could be on the README, what do you think?

**Comment by STRML** [comment]
That's a good idea, but it's currently in flux. I believe that right now all IEs have problems, but IE9+ will be supported in the next release. I'll make sure it gets in there.

**Comment by Surreal9** [comment]
Any updates? I've already started working on a project using this lib but it has IE9 support as a requirement. Not to sound demanding, I really appreciate all the work put into this library! If there's anything I could do to help let me know.

**Comment by STRML** [comment]
Understood. I've been swamped with work on other projects. I am working on finalizing a new API for `<Draggable>` which will cascade to an update in `<Resizable>` which will make its way here for a `0.10` release. I can't give you an ETA quite yet.

**Comment by Puffton** [comment]
Don't know if I mentioned it elsewhere already, but I would also be willing to help with testing if need be, perhaps a little shaky 0.10 might even be better than 0.8.3. I have already included 0.9.1 in my project and downgrading would drop new features like disabling vertical auto-compact, while keeping it in package.json stops me from using npm upgrade.

**Comment by Aweary** [comment]
@STRML how are you looking on browser support nowadays?

**Comment by otake** [comment]
@STRML Any update on the IE support? I know you are getting pestered by everyone about it, but I really want to use your awesome framework! Unfortunately my company needs to support IE 9+. Any news? I would just like to know if I have to wait a week vs several months... because I need to get this project started pretty soon. 

Great work by the way! One of the best layout frameworks I've seen.

**Comment by raptoria** [comment]
+1

**Comment by Aweary** [comment]
@STRML we'd really like to use this component as well but its going to hinge on browser support. IE 10+ is fine for us, but some clarification for the rest of the community as well would be much appreciated.

**Comment by Aweary** [comment]
@otake just a heads up, I went through the demos in IE9/10/11 in BrowserStack and it look IE9 does not work at all.

**Comment by rafaelmaiolla** [comment]
It doesn't seem to work on any IE, I tested the example pages.
IE9 - doesn't show any block
IE10/IE11 - renders the blocks, but anything else doesn't seem to work.

**Comment by STRML** [comment]
This should now be working in IE10+.

**Comment by yurikburko** [comment]
@STRML Thank you for your awesome component. Could you please update examples so they can be run in IE?
It seems that polyfill for String.prototype.includes should be added because IE does not support it (is used [here](https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L104) and [here](https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L724))? Thank you.

**Comment by STRML** [comment]
Neither of those uses of `String#includes` will break IE, because the first is in a `try/catch` (and IE is not Firefox) and the second relies on the browser being Firefox.

**Comment by yurikburko** [comment]
@STRML Yes, I understand it. But I want to run your examples from github page directly to test them in all browsers (e. g. https://strml.github.io/react-grid-layout/examples/0-showcase.html) :)
It seems that scripts are not actual on this demo pages, so at this moment I cant run them in IE:

![image](https://user-images.githubusercontent.com/1121550/70314028-c1a79d00-1827-11ea-82f0-75ca6446cbe7.png)
