### ISSUE TITLE
Quick question!

### ISSUE THREAD

**Issue by brianc** [STRML/react-grid-layout#79]
Hi -  I'm trying to fix some of the resizable bugs on the master branch.  Just forked this repo + draggable + resizable.  My question is...how do you work on react-grid-layout while also being able to work on react-draggable and react-resizable?  What's your workflow look like?

I tried `npm link ../react-resizable` and `npm link ../react-draggable` into the `react-grid-layout` folder but that doesn't seem to play nice.  How do you get it set up so you can work across all three repos without having to do long build processes between changing files?

Thanks!
Brian

**Comment by STRML** [comment]
Hey Brian,

Thanks for giving it a look. I am considering a rewrite of `react-draggable` to remove some of the internal state so it is easier for RGL to interact with it, which would fix these bugs. I haven't gotten anywhere with it just yet, I've been short on time.

`npm link` doesn't work well because React really doesn't play nice with multiple copies.

I wish there were a better way to do this, but I generally end up either symlinking the individual source files back to my local copy of `react-draggable` or `react-resizable` (so just `npm install` as normal, no `npm link`, and symlink the individual `.js` files).

You could do something a little bit cleaner by:

```bash
cd ~/projects/react-grid-layout
npm link ../react-draggable
npm link ../react-resizable
ln -sf $(cd node_modules/react; pwd) node_modules/react-draggable/node_modules/react
ln -sf $(cd node_modules/react; pwd) node_modules/react-resizable/node_modules/react
npm run dev
```

**Comment by brianc** [comment]
Thanks @STRML - appreciate the help.  I'll mess w/ that a bit.  I was thinking of just digging into my `node_modules` folder and poking at the .js files in there to see if I can find the bug.

What was first happening is dynamically adding panels to a grid the right-most panel will never allow itself to resize past its initial width, even if its moved down to its own row all the way to the left.  So if I have a grid of 6 wide and have 2 2-width panels on the top row, then I add a 3rd 2-wide panel on the top row to the right, drag that panel to the 2nd row, it wont expand past its 2-wide.  

So I upgraded to the most recent version to see if it was fixed and in the most recent version that bug still exists but also resizing a panel at all causes it to jump to an enormous size...so I think I might start on the older bug & wait on the huge jump in size until you've refactored react-draggable a bit. :)

**Comment by STRML** [comment]
Sounds good. The jumping issues were caused by the latest versions of
react-draggable and react-resizable, so |0.8.3| is still okay because it
is locked to the old version.

Dealing with components that keep complex internal state is difficult.
It appears that the components are not reacting well to RGL moving them
around (for instance, in the auto-compact). I think it is best in most
cases to expose two modules: a default that keeps complex state but is
easy to use, and a |core| component that calls back on what would be a
state change so you can deal with updating styles, etc., yourself.

Another hack that could be used to reset state is to change the |key| of
a component, but I’m not at all convinced that is the right way to go.

On 6/23/15 10:05 AM, Brian C wrote:

> Thanks @STRML <https://github.com/STRML> - appreciate the help. I'll
> mess w/ that a bit. I was thinking of just digging into my
> |node_modules| folder and poking at the .js files in there to see if I
> can find the bug.
>
> What was first happening is dynamically adding panels to a grid the
> right-most panel will never allow itself to resize past its initial
> width, even if its moved down to its own row all the way to the left.
> So if I have a grid of 6 wide and have 2 2-width panels on the top
> row, then I add a 3rd 2-wide panel on the top row to the right, drag
> that panel to the 2nd row, it wont expand past its 2-wide.
>
> So I upgraded to the most recent version to see if it was fixed and in
> the most recent version that bug still exists but also resizing a
> panel at all causes it to jump to an enormous size...so I think I
> might start on the older bug & wait on the huge jump in size until
> you've refactored react-draggable a bit. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STRML/react-grid-layout/issues/79#issuecomment-114536755>.
>
​

**Comment by brianc** [comment]
Yeah I totally agree with you about having 2 components.  Basically have one that is _completely_ driven by props and callbacks and then a friendly one that fits right around it and manages all the callbacks and pushes new props down on changes.  I've started doing something similar w/ flux stores too where I have a `State` component that handles the store changes and then just wraps another component & pushes all store state into component as props.

**Comment by rohitlodha** [comment]
I was wondering if the implementation would be simpler if we used HTML5 drag and drop API instead of react-draggable.

**Comment by STRML** [comment]
The conversion of `<DraggableCore>` is about finished, I just haven't finalized the API until I am sure it works with RGL the way I want it to.

I am not so sure the implementation would be simpler. React-DnD is much more involved to use than `<Draggable>`.

**Comment by STRML** [comment]
For reference (and this goes for any react component), you'll want to link the packages so they share a version of React, like so:

```bash
cd ~/react-grid-layout/node_modules/react
npm link
cd ~/react-draggable
npm link react
npm link
cd ~/react-resizable
npm link react
npm link
cd ~/react-grid-layout
npm link react-resizable
npm link react-draggable
npm run dev
```
