### ISSUE TITLE
Cells don't push each other away predictably after upgrading to React 16

### ISSUE THREAD

**Issue by tomhollander** [STRML/react-grid-layout#805]
Please mark the type of this issue:

- [x] Bug
- [ ] Feature Request
- [ ] Question

We're using RGL 0.16.6 with `verticalCompact = false` to allow cells to be freely moved and resized within a grid. When using with React v15, the behaviour seen when dragging one cell over another was predictable - the target cell was "pushed away" to a suitable nearby location.

After upgrading to React 16.3.2 this behaviour has been very unpredictable. Cells will sometimes refuse to move away at all (particularly the one in the top left), and when they do move it is often to a far away location.

See the following screen recordings for examples. (Our code and the version of RGL have not changed):

React 15 behaviour (desired):
![rgl-15](https://user-images.githubusercontent.com/10659986/39742904-89eba070-52e2-11e8-8996-81280baaf2fb.gif)

React 16 behaviour (not desired):
![rgl-16](https://user-images.githubusercontent.com/10659986/39742916-96180e1a-52e2-11e8-89e8-cea3dca5770e.gif)

**Comment by STRML** [comment]
Hmm. It is very much unclear to me why the React version would cause this. I am not, however, using `verticalCompact=false` in any of my apps so it will likely be a long time before I'm able to get to this. I recommend setting `DEBUG = true` [here](https://github.com/STRML/react-grid-layout/blob/5abce095edfd367d69a2efe8d21d0e7608610763/lib/utils.js#L64) to attempt to find the problem.

**Comment by jarjee** [comment]
Hi, I'm just following up on this issue. For future reference, it looks like we were actually on 15.2, and it was the jump to 16.6 that caused the regressions that @tomhollander was talking about.

It looks like the behaviour we were noticing has been fixed in the current master, when would a new release for react-grid-layout be made?

The exact issues that we were encountering with `verticalCompact=false` which have been fixed on master:

### Cannot drag an element into another if the width is smaller than itself
![cannot drag an element if the width is smaller than itself](https://user-images.githubusercontent.com/3888305/41946432-e1ee15a2-79f5-11e8-926c-7af07cd4d427.gif)

### Incorrect cascade on drag
![incorrect cascade drag](https://user-images.githubusercontent.com/3888305/41946444-f19d5bac-79f5-11e8-9bda-63625197ddcc.gif)
