### ISSUE TITLE
Rationale behind default responsive layout calculation

### ISSUE THREAD

**Issue by lgrapenthin** [STRML/react-grid-layout#82]
I'd be interested about what to expect. If I compare lg to sm in demo 0 (https://strml.github.io/react-grid-layout/examples/0-showcase.html), I see that the last column is the one getting all the items. The first item of the last column appears after some items of the first row and before some later items of the first row.

I expected row breaking at breakpoints, â la bootstrap. Of course I can implement the calculation for row breaking myself, but what is the rationale behind this default?

**Comment by STRML** [comment]
It's expected that the user will define layouts per breakpoint. What you are seeing in the demo is imply automatic layout creation, which is incredibly naive and is just slightly better than doing nothing at all.

If you intend to support breakpoints, it makes sense to define the individual layouts yourself.

If you have a better idea for how the intermediate layouts should be generated, I'm all ears.

**Comment by lgrapenthin** [comment]
The bootstrap default is simply to break rows like text lines, e. g.

1 2 3 4
5 6 7 8

becomes
1 2
3 4
5 6
7 8

Maybe RRGL provides too much flexibility to implement this as a default which is a trade-off I'd be fine with. However, at least as a first impression it seems like such a default would be possible. IMO it provides more utility, as I don't (yet) see utility of the current default.

**Comment by STRML** [comment]
Yeah, that seems like a sane default to me. I'll roll it into the next release. Right now, working on finishing modifications to <Draggable> and <Resizable> to reduce some of the state problems.

**Comment by lgrapenthin** [comment]
Thank you, this is all great work. Btw., it seems like a similar algorithm is finding new space when dragging. It prefers to append cols instead of pushing rows which also doesn't really seem useful.

**Comment by Puffton** [comment]
Ideally this should be configurable, I can see two scenarios. The one @lgrapenthin is talking about, and in the case of two column layouts for example:

1 2 
3 4

becoming
1
3
2
4

I'm using using RGL in a custom-built CMS-system and sometimes people put explanatory text to the left and form elements to the right. Then it would be quite handy if the text would remain above the form.

Since the users design the grids themselves, and I just persist their state (and then show the grids as forms without drag/resize), it would be easier for me to show them a dropdown with automatic breaking configurations compared to letting them define their own breakpoints.

**Comment by STRML** [comment]
Is this something that needs to be implemented in RGL itself? It seems that you could create your own series of layouts at initialization without issue. Since I can't possibly anticipate all the different types of responsive breakdowns a user could want, this seems like the best solution.

You can supply `i` as a key to your grid items. So, for your example above, you would just want something like:

`layouts: {lg: [{i: "1", w: 1, h: 1, ...}, {i: "2" ...}, {i: "3" ...}, {i: "4" ...}], md: [{i: "1" ...}, {i: "3" ...} ...]}`
