### ISSUE TITLE
Can RGLs reize from top-left, top-right, bottom-left position of div?

### ISSUE THREAD

**Issue by LSYUN** [STRML/react-grid-layout#849]
Thanks for RGL, I almost finfish my layout mission, except that, right here, I can resize div from buttom-right  on divs,  I want to resize every div from last three angles(top-left, top-right, bottom-left) as well. Is it posibile?

**Comment by pingbaohua** [comment]
你好，你现在实现该功能了吗

**Comment by rskarras** [comment]
Hey @LSYUN the default resizing action works by adjusting the height and width parameters. In order to handle resizing from any of the corners other than bottom-right the x and y values would need to be changed. Any action that displaces the top-left cell would require such a change of the x and y values.

It is certainly possible to accomplish this, but the library is not set up to handle this out of the box.

**Comment by LSYUN** [comment]
> Hey @LSYUN the default resizing action works by adjusting the height and width parameters. In order to handle resizing from any of the corners other than bottom-right the x and y values would need to be changed. Any action that displaces the top-left cell would require such a change of the x and y values.
> 
> It is certainly possible to accomplish this, but the library is not set up to handle this out of the box.

You inspired me!  Changing the x and y values would be a way to make it out. Thanks for your advice!
