### ISSUE TITLE
Is it possible to change layout after render?

### ISSUE THREAD

**Issue by developerswebb** [STRML/react-grid-layout#860]
Is it possible to change layout after render?
We use your component with our settings(for i.e. block-collapsable-header-title)
Block-Collapsable-header-title. http://prntscr.com/kzc0ir When you click on block - block collapse to one-header-line 

Example 2 with resizing block and return defaul-block-size.
We try to calculate positions, but it's to difficult https://gyazo.com/6ee398737a6a2205f1365c967cc1734a?token=e3f0361e5d8c3b5358b25cee2e98a73c

Is it possible to change layout after render?

**Comment by fairps** [comment]
Based on the code I would say that it is supposed to work, but I am also having issues with this.  
I have my layout in a layout in a state variable and I try and remove one of the items from the layout.  Even though I can see that the item is no longer in the layout using the React tools, and i am no longer drawing the item, there is still a hole in the layout that has "substance" because RGL believes something should be there in that spot.   
The code uses lodash.isEqual on the ComponentWillReceiveProps call to decide if the layout has been changed.  I'm even using a new array when I update the state, but it still ignores the change.

**Comment by fairps** [comment]
It's not stale, just being ignored

**Comment by hellhoundsx** [comment]
@fairps late response, but maybe some might still have this issue, the solution for the flash not to happen, add a elem to the layout which you hide with css, and right after set the correct layout without it. This makes the grid to update without flashing....

**Comment by fairps** [comment]
Great idea!  Nope not too late… in fact very timely as I am just beginning to pick that project back up.  Thanks! J

**Comment by seanaguinaga** [comment]
@fairps do you have the code you used to do this?

I am not quite sure how to accomplish what @hellhoundsx is talking about
