### ISSUE TITLE
Toggling isResizable or isDraggable causes new instances of children to be created

### ISSUE THREAD

**Issue by tlrobinson** [STRML/react-grid-layout#89]
When toggling `isResizable` or `isDraggable`, new instances of the child components are created, which causes any state in those components to be lost.

**Comment by tlrobinson** [comment]
(As a workaround I'm leaving `isResizable` and `isDraggle` enabled and selectively capturing the mouseDown event if I'm not in editing mode)

**Comment by otake** [comment]
I'm having the same problem. I would be nice if you could easily toggle these options.

**Comment by STRML** [comment]
Unfortunately, toggling this option causes the entire `<Draggable>` or `<Resizable>` wrapper to be skipped (because they can't be disabled), which understandably creates a new child component. 

I wouldn't want to always create them even when dragging/resizing is turned off, due to the overhead. But we could disable them if they are already present.

Technically, we can now easily disable `<Draggable>` by setting `axis="none"`, but both `<DraggableCore>` and `<Resizable>` should have easy `disable` options.

**Comment by STRML** [comment]
Going to close this in favor of #206, which will track passing raw props down to resizable/draggable.
