### ISSUE TITLE
Height calculation is bugged.

### ISSUE THREAD

**Issue by wisniewski94** [STRML/react-grid-layout#978]
### Expected behavior
When ```rowHeight = 10``` and grid item ```h: 6```, item grid height should be 60px. 

### Actual behavior
It's actually 110px;

### Steps to reproduce
GridItem.jsx:204
```js
Math.round(rowHeight * h + Math.max(0, h - 1) * margin[1])
```
Should be:
```js
Math.round(rowHeight * h)
```

No idea what Math.max actually does.

**Comment by wisniewski94** [comment]
I didn't take into consideration that if grid item height is set to 6 it will be calculated as (1 + margin * h). My bad.

**Comment by tonix-tuft** [comment]
@wisniewski94 Can you explain why the calculation works like this?

If I have a grid item with `h: 3` and a `rowHeight={150}` (`150px`), I expect the grid item to have a total height of `150 * 3 = 450px`, but instead the grid item has a height of `510px`...

**Comment by cention-sany** [comment]
To get the quanta of height, just do the backward math will do. https://github.com/STRML/react-grid-layout/blob/83251e5e682abfa3252ff89d4bacf47fdc1f4270/lib/calculateUtils.js#L136 instead of multiple by your rowHeight, use your expected (height + margin-y) divide by (rowHeight + margin-y).

Probably the reason for that can create a more consistent layout.
