### ISSUE TITLE
Resizing issue on firefox. 

### ISSUE THREAD

**Issue by pratikguru** [STRML/react-grid-layout#979]
I've been having issues with responsive grid layout on Firefox for desktop. 
![image](https://user-images.githubusercontent.com/23006473/62995864-50c31c00-be17-11e9-89d1-09deb5b0d91a.png)

The top left image has been resized to a smaller dimension than its initial size, and it the content of the graph is popping out of the grid. 

Any body else faced the same issue?

**Comment by josesaranda** [comment]
Maybe you need to set the container overflow hidden, and resize the chart.
What chart library are you using? I think this is not a react-grid-layout problem. I think this problem was generated by your container and your chart...

**Comment by pratikguru** [comment]
The charting lib is from Nivo and yes this problem is specific with firefox only.

**Comment by n1ghtmare** [comment]
Any way you can set a _minimal_ example (you can use the [codesandbox](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) if it helps), so that we can reproduce the issue.

Like @josesaranda said, from the looks of it, this is not an issue with react-grid-layout, but rather with the charting lib.
