### ISSUE TITLE
Responsive layout doesn't work unless window is resized.

### ISSUE THREAD

**Issue by skyorion427** [STRML/react-grid-layout#984]
When the parent element of the gridlayout is resizing, the width of gridlayout is still the same.

Gridlayout is resized only when window is resized.

https://github.com/STRML/react-grid-layout/blob/master/lib/components/WidthProvider.jsx

**Comment by mankinchi** [comment]
Yes that's correct. It's because the WidthProvider is only registered to run when window emit resize event. As you can see [here](https://github.com/STRML/react-grid-layout/blob/master/lib/components/WidthProvider.jsx#L46)

My suggestion is that you register the resizing yourself then use state to trigger the layout to rerender.

**Comment by josesaranda** [comment]
Use `window.dispatchEvent(new Event('resize'));` when you want that react-grid-layout resize dynamically. I use this when the container layout has resized.
